repos:

  # - repo: local
  #   hooks:
  #     - id: run-tests
  #       name: run tests
  #       entry: pytest tests/
  #       # args: ["--ignore=app/migrations/env.py"]
  #       language: system
  #       pass_filenames: false
  #       types: [python]
  #       stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args:
        - --remove-all-unused-imports
        - --remove-unused-variables

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: [--safe, --line-length=100]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
        args:
          [--style=numpydoc, --no-numpydoc-name-type-spacing]
